sudo: required
dist: trusty
services: docker

env:
  global:
   - DOCKER_OPTS="--rm -ti -v $(pwd):/mnt -w /mnt"

before_install:
 - docker pull rohanshahcsiro/mpmap2-ci

install: 
 - docker run ${DOCKER_OPTS} rohanshahcsiro/mpmap2-ci R CMD build .

notifications:
  email:
    on_success: change
    on_failure: always

after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;
- find *Rcheck -name '00install.out' -print -exec tail -n 100 '{}' \;
- find *Rcheck -name '00check.log' -print -exec tail -n 100 '{}' \;

script:
 - docker run ${DOCKER_OPTS} rohanshahcsiro/mpmap2-ci _R_CHECK_FORCE_SUGGESTS_=false R CMD check --no-vignettes --no-manual mpMap2_*.tar.gz
